#Application Server
server:
  port: 8080
  address: 127.0.0.1

#Homepage Index
index: ☆☆IndusfoCloud Stage环境启动成功☆☆


#DataSource
spring:
  datasource:
    username: sa
    password: 123456
    url: jdbc:sqlserver://47.94.89.221:1433; DatabaseName=homework_project
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 500MB
##Mybatis
#mybatis:
#  mapper-locations: classpath*:/mybatis/mapper/*.xml
#  #check-config-location: true
#  #config-location: classpath:/mybatis/config/mybatis-config.xml
#  configuration:
#    map-underscore-to-camel-case: true
#  type-aliases-package: com.indusfo.spc.sdk.domain


